[[MSTM]]
arch = "aarch64"
git-tree-sha1 = "0fea25c44c195b80592516495eda5cde45cda097"
libgfortran_version = "5.0.0"
os = "macos"

    [[MSTM.download]]
    sha256 = "5bcc2524a5f1cace685b4975011e828816ee8785b4734ea08ed7a1bd9e7e91e5"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[MSTM]]
arch = "aarch64"
git-tree-sha1 = "930946cc117244cbc2936a83a159082b41d0cc71"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "dd778891296d1510f680b7f0efcb372bad7b84b5c861766257e453c5e7490bb6"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.aarch64-linux-gnu-libgfortran3.tar.gz"
[[MSTM]]
arch = "aarch64"
git-tree-sha1 = "e0fa8c6bcf8d0a1bb6c284ca3453d56cba4261a0"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "b84243a0d7c5a0beebe45e4d1a518d4cd1ea6fe5693b4f591b480a64abe899b0"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[MSTM]]
arch = "aarch64"
git-tree-sha1 = "3e244418a746ff69d86b2896240eea888b8371a1"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "ccd122776674cf3b735725843cdef2cbe346a0275201a4462bc6dbecad9fa36c"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MSTM]]
arch = "aarch64"
git-tree-sha1 = "120c136e1183ca0da88bdf304bf7a52dc163f075"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "f66e9c20b2e4de8e818c544b9c6faf1d1965b7e3169df756d3fdeb65263e90c8"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.aarch64-linux-musl-libgfortran3.tar.gz"
[[MSTM]]
arch = "aarch64"
git-tree-sha1 = "89761b194b49a6f0aca5fd4e7a71a66e136f3964"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "27392ddce07c7649d2c78148ecaa47f01e8bb546a154762dbf1daa39d9255e38"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.aarch64-linux-musl-libgfortran4.tar.gz"
[[MSTM]]
arch = "aarch64"
git-tree-sha1 = "c2c3e4c72402d641c2e063b77b8412bae422a7d1"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "ea5fa64f37b30abb4a0ac3df18ea1f12392eda902dde71f4d5c20f54f9ffc163"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[MSTM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "914d423196b9630e02bc8202a3ae5d7443fa3f13"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "f11d9ad047901d8ddd63cf88a99e9a503112c479e59e31b62d7d0c2ee3dbd54d"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[MSTM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e1b6bc39d551e79a030db8eaaf78359d4661ac02"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "32e6db26db7d6a48dacec8942127eacf2f71be1145e122984f3c273385f40188"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[MSTM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5e726e36a4469497cdd548a08e89c60f96ffb346"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "6bc9e6bb0994f04344a731ee8a2cef2f7ec1e2ec1aec705dfc31c089ed8a1283"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[MSTM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "def8d606bd3d48ba2aa53c9e9b30308f76fef964"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "6520d9bc3fd8dfdb9283533d2ffe369799eabc8686521d3240a1d05205fc8165"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[MSTM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "435c5df7f2cf4603805e1cb8f28934493549d394"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "88d5772e9859d6003e8eee5b82eaef4ed22223b419a74b29677fe5b771b55302"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[MSTM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "eb8e4ef885f9196a6ba4462d217d3fcda98840b8"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "b9bf8cd4734e1241ac6ccf483b5e38b18d4f1eb9130480b69d3a35e13cc752d5"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[MSTM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8591574fdbfb649712ab569329b864f6e3c90c12"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "124ad514bbae2ef8ef833580b91d56f265c671feb6955a4327c570fa05383690"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[MSTM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e391f6e1dfea62b28757272babbdad39a6fa2521"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "3dfd26c9e5e0ea4d8681f9538d5d8351af559be855523a6c0abc415881995fdf"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[MSTM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3ec274a6f3a92923c4a3f749d0ece863c46f8968"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "9a218d47c5063e892b0d9ea898124d7ab75ef98706dd41bac46898860c309bba"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[MSTM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4a78f316de543e57f96a7572645adfd83743baf2"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "d8c3464c9a48bf330a5998d59e2b4ea0f95064567fe2afcea74c8e9c390093f8"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[MSTM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b8a5db7a2cc065c702af9d2b01cdaac0475433f7"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "56695af1a8efeaffd692d827ddf071276b141e7c4894b9a44e55a4689c3c87f6"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[MSTM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cf3b2749a0093bd1dcd4306c45f686ec512c8a34"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "1d500e4ca086c50fabe06da22414215495e67057785a0c75328f7614422ffc6c"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[MSTM]]
arch = "i686"
git-tree-sha1 = "93f37bc3aa3b4e4063bc8ccf5f88b3ca9e9ea79f"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "6495e2af2727b182820fab60f26f3cc331c75d647b810535e82e9c734cd959ec"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.i686-linux-gnu-libgfortran3.tar.gz"
[[MSTM]]
arch = "i686"
git-tree-sha1 = "294b1bc0d4b14108f9b9d4a96fc5a21e396b7feb"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "9c459711bb7cbe746d551d349058138f20041cc6eff785a22a00c12f1582dc6f"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.i686-linux-gnu-libgfortran4.tar.gz"
[[MSTM]]
arch = "i686"
git-tree-sha1 = "6cec73c363a5beb1164de7523a5999df2e9c91bc"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "cea18a7e6c333b15d690ae066bc0214d142e6b0eddc4cb0e0ccdff4da4ee15b0"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.i686-linux-gnu-libgfortran5.tar.gz"
[[MSTM]]
arch = "i686"
git-tree-sha1 = "8216440144934e7600589cdbce600ddc7687ff0a"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "1f1175370df0a9c10a98d2307359effcf2be9a4a8efda0927bfa8cbaac166d90"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.i686-linux-musl-libgfortran3.tar.gz"
[[MSTM]]
arch = "i686"
git-tree-sha1 = "89930e91282918524ee0d1b49b3b6179f337e970"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "54cf47911c852b74a5a90be0dd629a7902cd689e9f3c0febab9e7110bf9b3f51"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.i686-linux-musl-libgfortran4.tar.gz"
[[MSTM]]
arch = "i686"
git-tree-sha1 = "781ef1894699279b83d91c152ba99409c88393e4"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "c1401570599c0be4a0684dd1e259e503ce4f24f2711a8b33c9face673146e5e9"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.i686-linux-musl-libgfortran5.tar.gz"
[[MSTM]]
arch = "i686"
git-tree-sha1 = "7d0fd9b5c3b8c3a1327376c889498a3127e96942"
libgfortran_version = "3.0.0"
os = "windows"

    [[MSTM.download]]
    sha256 = "028902f3b08bf489026657b54b3a3b824be531170b40f646b140b5130832543f"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.i686-w64-mingw32-libgfortran3.tar.gz"
[[MSTM]]
arch = "i686"
git-tree-sha1 = "a8a2ef5c40397d3579186a9fa769903eb3cbcf61"
libgfortran_version = "4.0.0"
os = "windows"

    [[MSTM.download]]
    sha256 = "dbb1fed5b6545a0c3ad2f75913546b1efde80968ba9c0fb009b08b8692fabd06"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[MSTM]]
arch = "i686"
git-tree-sha1 = "64bd50f961c9fdddebfe671ae4e64e4e360ab3cd"
libgfortran_version = "5.0.0"
os = "windows"

    [[MSTM.download]]
    sha256 = "63b78602477111e69e530ad7dd8d165d112bbe07f19dfaa9e8da64bb31c15785"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[MSTM]]
arch = "powerpc64le"
git-tree-sha1 = "168337a5d2323eadfbdafb1189f44d6ac2484a33"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "5410acfcea64bc2fbc299d76f3ecbfb4b4510ae6cf801b8942be429617604d8e"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[MSTM]]
arch = "powerpc64le"
git-tree-sha1 = "5f552c58a7f58d99d2d1db812a04aabd1a7bd7fc"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "36f527ef7111b49bf06cd285f75475c4f11c8f7ede2fb76ae1d3fb8831204c1e"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[MSTM]]
arch = "powerpc64le"
git-tree-sha1 = "835c2c8568e96ddaebdb6854cbde6257889351b4"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "4bc1359119f0f5e94fcb76b99884bc43db1bcf705e8d03072a348bb3f6af2817"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "da401bcf099959067bc9605c30a635e919a2471f"
libgfortran_version = "3.0.0"
os = "macos"

    [[MSTM.download]]
    sha256 = "7bd1d1986945f649223461102ae563e1a80f35bd7d1e3da1aeffaede959f9ffa"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.x86_64-apple-darwin-libgfortran3.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "6495f3aa56cdecbe322253d1e39c53ce76365fbe"
libgfortran_version = "4.0.0"
os = "macos"

    [[MSTM.download]]
    sha256 = "5f356a6a7bfe0476441cd2703e0aef06aa943863844589522f6bcae68e933dc4"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "81d0bd97058d17b187316386569957808bd2f7d5"
libgfortran_version = "5.0.0"
os = "macos"

    [[MSTM.download]]
    sha256 = "f1d0c5fdc250629d5b5622186c61071134a44b7bb453bd74286164c420d1b3db"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "378482bd09934713635fab93c5d074a5a8f564f1"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "0ebb6fc8f96f2dd1de7c85223bdb56b300b3f2470602d56557e0af3223626f8d"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.x86_64-linux-gnu-libgfortran3.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "74adf7016fa0ada5008c659746777a5428c8a2fa"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "d32f7cf84030eb54f4ee4093d2ad2e36a45f97d1cccec1449cc22d9ac9ed9554"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "94ed4ec3e98daf8ee972461b0fe788bdf695accf"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "2a17a090efd0817830d4d3aad81c7996be9736985f35653e9a17449a9c98bd8c"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "732bdd3106f071cba1bab8b030634a0ecd8418eb"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "e49f8ceb6ec4b6349db327f6173ce8417710f52fb25d1928a56ddfc0ef291bbd"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.x86_64-linux-musl-libgfortran3.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "2f8980590f4384408a91f32228445da94d324d7c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "dc762ce00478efa74d56c3f9429846817edc5a15eb779a625cbcc75e298e3282"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.x86_64-linux-musl-libgfortran4.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "6d76550e0f644237b8db27751f64ea4a70725820"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "5e87ed0c6c16daea5793419796a7677b1170d74c82d626dbcaf474935e7443f4"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "f82cb28828c83d89217fca215a2df610c04d1692"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[MSTM.download]]
    sha256 = "c4df85ed4da18f721d687bc071b564d47b9504eed47ebeed805c706b3c22ec1d"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "ec9b6395702dcd8b9328ea2450c82b75d070967c"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[MSTM.download]]
    sha256 = "25f09e9c8307a0183d7a88f9e510c799d39aba704d4d180ac919cd7d05ab7b22"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "fa5ae202e91593fb11038c90ceb9eb63429d7342"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[MSTM.download]]
    sha256 = "7b7dd7244876b1e54db99e247e03424dcf62a83be36be1cddf671728e9fcab25"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "89ec2ce0b87d9d3204401c5e4ccb554944ef6a23"
libgfortran_version = "3.0.0"
os = "windows"

    [[MSTM.download]]
    sha256 = "6ec99c926ae034497a2d9ec783c5470eb7215221917735c6fc4c1b6f047608ab"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "68fe8f627c1c68de11188501d075e542bdd849e7"
libgfortran_version = "4.0.0"
os = "windows"

    [[MSTM.download]]
    sha256 = "1d40e1f769b6f9b4790df93a7e1475d8cec6c52cc9376ec3b9010d4ddbb11048"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "d7ecb47345264d1bc800b048d79aca5b284895c0"
libgfortran_version = "5.0.0"
os = "windows"

    [[MSTM.download]]
    sha256 = "5430d48fc72895f62f1f5b6e7af5fc94ecb6b1cbd3a3974c773c38eeccb31cfa"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.1+0/MSTM.v4.0.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
