[[MSTM]]
arch = "aarch64"
git-tree-sha1 = "9d60929d22dc07c788568f6a608daa730799f931"
libgfortran_version = "5.0.0"
os = "macos"

    [[MSTM.download]]
    sha256 = "03e883064c28d71400ab13e1b092e8c4c0099dfd8c29ff1ae39b0adf1bf88ab5"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[MSTM]]
arch = "aarch64"
git-tree-sha1 = "b35ebe042524bade4b0b1da33ec4a90007e6bb4f"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "b0aa3edbc7c5f982988fbd6b84bc688a207a253b6ca922fe66b9ee9ca5cd779d"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[MSTM]]
arch = "aarch64"
git-tree-sha1 = "5bdc602b9aeec50cecff2051665dfc2fa67cd939"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "10546dce8afd472a69a290f9f57f7f153d4d3571b8ab773f8fb6af87de0309c7"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[MSTM]]
arch = "aarch64"
git-tree-sha1 = "9e30de7cf0a3e7db6fd3806806d3dd16c94408a4"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "c3de4aab00fc763fbdb5028f64874280fcb52633c73099d083151c21478f90b6"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MSTM]]
arch = "aarch64"
git-tree-sha1 = "0318349ee2be248d21cbaa92992282e6a6ada481"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "d4b944ae68fbc908a08f0a0511db488207379234fcdd0cc6ef50f62dff196b9f"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[MSTM]]
arch = "aarch64"
git-tree-sha1 = "59353b2e67d2200a2ae6b0f0d3a669cbdb6cfa0e"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "6ff7c040e14ed2ec316a212a0822224b0c9dcc4f9ff935966df9edac1c548cc9"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[MSTM]]
arch = "aarch64"
git-tree-sha1 = "2b78b40f82ed76a9760547c450d3f2b4d944334b"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "d4ed11bc395d6eb901543d6c3a33e36ec3fc9a089c949617c20400da1b59dac6"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[MSTM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b045801368e173c9b62ea3a9ae3147d17011fa4a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "eb78f38bc12cfdf0d9db92df53e061d7ff86a3f359b8f8365f533f336e15233b"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[MSTM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c682be5b2536c28979d23138bb5676514d38bc88"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "1270d61be699eabea08770c63a43e18acf7b9a305fb3ae964e93b758f1e5234b"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[MSTM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d08c7cc3f4850f508f76c5a85164c8199ec3445e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "6d2ace3332198ca0cc54978a8ca440669cc1f84e1b23546cb44304c25acabee0"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[MSTM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0d94ae61737c21d829d9b9cc91dd8725d008ac45"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "2bf2592daf194366ab9a232face41c27f962bc7f0e9958c33a037731b9f50790"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[MSTM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0244f2fa39fbad47f0bc26d3cc7e4808a64bfddb"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "5f4728c1ddfb5598c8bbb21155aadba82c190978ff9d02c4c166a2d22c42ad9d"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[MSTM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "97136406aea3cd3d08ae4ec403727041d9ee45c2"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "83980d6490e67e720ceab6b5ef86b843c6c332c1660f0e7fa4be14dc9a4362e6"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[MSTM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e7220a6307ef8044434ea44a6c60f22c8871cc83"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "e997651b91a470c86c5837b3f4117146dc397364acfda8d05e679abea6c79b44"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[MSTM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1b2cdc963eb2a1868907cbb6dad996af21790002"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "98c9c5a644fa315916a860ec470e7b07ca4ddb5566aa633513abf969d4765433"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[MSTM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4f85a9164b00d11e864fa1788e8ad9d8b02630c1"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "c8cfb3dac1c382c681e45762a3106700b38b5f900a306aee017e87a5b4688fcf"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[MSTM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1f425d06177c9bf9600f339fb2f46e62a1700ec0"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "fdb8e3c82b00468e546a17027864c5060293f67aae1985b4667d498562891f60"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[MSTM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f14d50eebebe313da2c04524272a54b2819cf76a"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "f84fe8c7afc1b9c671cb0bdb8746e7fca5026f24de87f0809d59ea005ae38eb1"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[MSTM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b7552546291863c0f7a2bd30009fc2a751ca3793"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "41755aad7293e1f2701b62e8388d03541ea6a0198b1a467ec4ea9db972e3a510"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[MSTM]]
arch = "i686"
git-tree-sha1 = "8947fc357d7f3c00ab57ba59c2f104b09d264113"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "b6e43dc150fb7345be1aea43cd2f0729891fed53532dbfa0efc53815bdfed6c9"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.i686-linux-gnu-libgfortran3.tar.gz"
[[MSTM]]
arch = "i686"
git-tree-sha1 = "5bc195f538ab1400203d8a7116961257649f8996"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "98e31255284c7776d261191a9316175a6f33a4b09b514fba30e3e9025fe4da58"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.i686-linux-gnu-libgfortran4.tar.gz"
[[MSTM]]
arch = "i686"
git-tree-sha1 = "418c0aa8b80bf64bdf5929dcf827956cea514475"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "13171ed9f359d647e1d98a572bf732894cc2481b3cb799795612c275335bbacb"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.i686-linux-gnu-libgfortran5.tar.gz"
[[MSTM]]
arch = "i686"
git-tree-sha1 = "3895141b942e2446b859ff64b8f523f584a5d94a"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "2f9120fee49e98c63d607a369cf4fc978fcd7058132cb235ab2f88367eaf575c"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.i686-linux-musl-libgfortran3.tar.gz"
[[MSTM]]
arch = "i686"
git-tree-sha1 = "e2d133a004d3fd75ae479c9ad8d9ed7207781039"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "76ac537790d7d51aab6f5a7af43622a739c418bfee318244c54036834e86b10e"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.i686-linux-musl-libgfortran4.tar.gz"
[[MSTM]]
arch = "i686"
git-tree-sha1 = "0fe498992c5aa7c9445a29df1c8b99c1902ec7fc"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "a5e680f96260076b132cdf44b792d28741a11ed3d07acabd1f7056cc0b8d4a18"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.i686-linux-musl-libgfortran5.tar.gz"
[[MSTM]]
arch = "i686"
git-tree-sha1 = "2a78f483e5d32261f9f7ff991d2a7a3ffd9f5a33"
libgfortran_version = "3.0.0"
os = "windows"

    [[MSTM.download]]
    sha256 = "2e4e980fa268c6af128d6ef97ce1a5d7320a616033d805dcd23266358c8e85fb"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[MSTM]]
arch = "i686"
git-tree-sha1 = "2cb695642bb40916d9ed7ab41da0d06b02e00c15"
libgfortran_version = "4.0.0"
os = "windows"

    [[MSTM.download]]
    sha256 = "fd356d17368ebe8c06d558f4f1b3b9c4813739661a6e1b58ac71fbb4d2be84fd"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[MSTM]]
arch = "i686"
git-tree-sha1 = "e5c4257a29a0afb9b709ad713da1a9ba38e169be"
libgfortran_version = "5.0.0"
os = "windows"

    [[MSTM.download]]
    sha256 = "da57a30f852b144c2acb8315398f31500ba7b5af655250c54692bc9d4a12af42"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[MSTM]]
arch = "powerpc64le"
git-tree-sha1 = "f1e52c0447e1d3286af485108b1016c77bb667f6"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "04e2b0f3937fdaf9f30a3c0f7c8756fa3ff3eb12924e66ca0659c103716c9b6d"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[MSTM]]
arch = "powerpc64le"
git-tree-sha1 = "a7fa48e606b8ef1ba2ee547972f3910def35622f"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "16769191e555e8760f1b83abda2113a172c249f158dec86e3a647eec9b8b6562"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[MSTM]]
arch = "powerpc64le"
git-tree-sha1 = "de3f786042546905365365a9cbe05482889cb57d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "cd65c3bc808a8ce93bd3ce39f00453849e6998fefac5fb8eee986568e5e1a306"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "cd8ae3a8da1eff98529061cc92e0f023d237a952"
libgfortran_version = "3.0.0"
os = "macos"

    [[MSTM.download]]
    sha256 = "706910b6d15db266ced920f03e71131a4c737d13eaa6e68468d7bb98739a4556"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "435fae1ef712805a3a241188a6773d59eb7431a5"
libgfortran_version = "4.0.0"
os = "macos"

    [[MSTM.download]]
    sha256 = "9453374b7cf4c2f1cd9b512ebf99002b5e14ff3212f67448eca2ad09a2ba4bbd"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "0d618fc53e031142b5bcd501a0d101254cc39cf7"
libgfortran_version = "5.0.0"
os = "macos"

    [[MSTM.download]]
    sha256 = "b63d82fe9218bedd30b950d83ccd94bca2b0aa22dc6be1456f632b9659ff2ebf"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "c67c45332a6914b0081d7e8ebc50ca8b18b45bdc"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "1cea0fd409a05754cd8046307d287ed1724b590e1d8b86a796006f4a6eb07f23"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "69f78c53a16925293818f6a4d0b7d26aae058e5f"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "129b560145546a634e6984aaeeb1594a577c63c7dd91623076f34b36b5993c02"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "5f42bff66a48498beb11bc4698a7c1bca06c15c4"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "2b1053c1ebbd462e7ad4e3ae37b7579a1ec8d30607de62d67ef909e56bc6c824"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "896b9b62bae4c7a72f40a47a67f1ed7b4ce420ed"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "f54a643a1e2f7e3aab3fae7a265abbd3bdb9ee82e2121ca10b4d2b076e420b32"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "1ff44e157d395efa70c855cac5a4b88ac8b73d41"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "d5f505b653c445725718664f2c0e73d344aa84f0ba6bc5c410669a476562cf73"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "75e2079baacffb966a5f75e0f1ee1fff806359ee"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "8f1b95129a98fe1c53645b886af6826531345ebf31cfddea5932e72ba4965f09"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "2c4cbbebc59225d62a315017c86fbd81c0437f42"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[MSTM.download]]
    sha256 = "2e89e5c51574c1a26f8de5ddb4f78c865567aa6a936c317e79af31031310d0f2"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "5383a6cb5f961cb8b13c186bffeb5e462cf89d9d"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[MSTM.download]]
    sha256 = "2ff0c75973affdb543e2facf37d0836deb650e780e2d1d755d54f2d22e3b0db4"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "b3de4c6a779db7f893e666387b9b2ef1a2c85445"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[MSTM.download]]
    sha256 = "74deabbc5c1c48c44dae93e631724e0b240fd8fe714a9ba7a86a4f65a28281c4"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "65a28943eb4713a18547237622471d95d24cc55d"
libgfortran_version = "3.0.0"
os = "windows"

    [[MSTM.download]]
    sha256 = "069fa5ca3fe6a8ffca6867cd110a2a7810c31907b388e7b69ad0a37789392f0c"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "0ca4b581c35f4fa3b3607ea8943d9b9617ce78bf"
libgfortran_version = "4.0.0"
os = "windows"

    [[MSTM.download]]
    sha256 = "183e92714b38b910892142a3f6ad822dccba4a480ba99e2d4add50d126ff912d"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "b3c102f553ca99798bfee1e0036c8182fd7bec25"
libgfortran_version = "5.0.0"
os = "windows"

    [[MSTM.download]]
    sha256 = "66457bc1ce5574a291ef6f1bf0a24fb1f557a83242ab246c2519f893dde838c7"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+1/MSTM.v4.0.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
