[[MSTM]]
arch = "aarch64"
git-tree-sha1 = "b7af09b0d27ed209f97538754ac16717366363f0"
libgfortran_version = "5.0.0"
os = "macos"

    [[MSTM.download]]
    sha256 = "4d39cf447f179b30ec94c56654a337f5a1d41d3db14d2fdcc48a027ef2cd53f2"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+0/MSTM.v4.0.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[MSTM]]
arch = "aarch64"
git-tree-sha1 = "34442c6d35e6e50d320d9356021b6f3c4039a7bb"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "ef4fe7ff475648ccec7379db9e30be05ecb79b4c48b78d2ee448d65d4149e5df"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+0/MSTM.v4.0.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[MSTM]]
arch = "aarch64"
git-tree-sha1 = "60905db22b5d0b977da5bb77b67ec3eeba7b1026"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "fc8abdbcaaa650d9d75f56503c4a4d8f19a3445835476f7a79f8dc4079af6407"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+0/MSTM.v4.0.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[MSTM]]
arch = "aarch64"
git-tree-sha1 = "c8606ca01a3aa93b47d5022327f24a1ab6ebdd8f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "6216b2549a56f55e76f754bafaa6b24f4cea3e0f5999573cde542b12c2a30704"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+0/MSTM.v4.0.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MSTM]]
arch = "aarch64"
git-tree-sha1 = "92f359114f146084e9a36990c5037b5be2ffdf42"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "1ce3c13e64318eff834850af93bd90791dda446fd0f79b99840aff7494f29e32"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+0/MSTM.v4.0.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[MSTM]]
arch = "aarch64"
git-tree-sha1 = "641bcb37891f56b899f87a11d9c09018ce7c2bdd"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "7faacdd637ae3c4623258414297361bfd0f116e3a7270875f9f2332449f08bcb"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+0/MSTM.v4.0.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[MSTM]]
arch = "aarch64"
git-tree-sha1 = "9987eabaafa6efbc189eb7d24f62ccce52f197e4"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "41852eda16a0a0138bbdfa2dfa909fa146803019b20df38db269f955449c6a2a"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+0/MSTM.v4.0.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[MSTM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "256e0efeff6a0a67210b934561860af71e287434"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "9a949c7e8d1379af27ecd5bd868dcfeb093a9441d42bb712dfae8f26b566d784"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+0/MSTM.v4.0.0.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[MSTM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cc52ea15732d0c483ae61472262a9f3ef6265cf4"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "f1eff99dc5ca3d83a04e7bbf477a7fb20527ac8ee974649af14bfe14793c7226"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+0/MSTM.v4.0.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[MSTM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cbdde074eee92399317cede496bd73e2062d2d80"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "acda205c9aea55b7a7af4d751538a191d35a16554332f88c5939313c002ec352"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+0/MSTM.v4.0.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[MSTM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b3ffc132be15267fe969e7898a3199729a077ccb"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "6355f4f56cd7836b43ef20a5af3b14f59243bd7135a2b07500c362df09ba0db8"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+0/MSTM.v4.0.0.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[MSTM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a565cfa862c51ff244c6724e6fde1d41ca30f14a"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "c3cc236d26cd25f9bdb3b346cfa20fb203cff0e7b9571c507a6bc15960d81517"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+0/MSTM.v4.0.0.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[MSTM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6e2bef81abd4054b06bc12c454953365a20f31a8"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "d7eb885a8e3abe91b686ba827636245d21b0d1f8a2e5c12fa963ddb5d1e3be9d"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+0/MSTM.v4.0.0.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[MSTM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dce5aa8cfcc77b2e11a30b1863ebb338dcc14e1d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "d0d0215f0c11258f905ab9c2a8c76835286251655001cdd32335e1bcf7f5e0a2"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+0/MSTM.v4.0.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[MSTM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ece7e96db5fd14ab78c5ca32b988b32a7ea5d0d5"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "931bfa25ac47624c018dea37e7555f9087656b27c619579a86e9169a9b5c17ec"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+0/MSTM.v4.0.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[MSTM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2980c7dd9298574d97c4bdfa79c4f56fa0f0a9d7"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "a033b46756141fc861777fb6feaa4da1213453a76530d4c8b82037f3ddd76e93"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+0/MSTM.v4.0.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[MSTM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c9ddbd24d533b319b485ff185a68214e9b316f4e"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "a54c8ed5958c72c73493c18958537ae472902ca9e04cde30f7ccf69ce4ec2682"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+0/MSTM.v4.0.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[MSTM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "930d1da34809adfbbba6619b8deb1715ca284667"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "89ba7a3af659ccfbff24a4935418a7bc7c05d28d96d54997fdcc5a2906846ae2"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+0/MSTM.v4.0.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[MSTM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3251e6f8a2b99946de720d0abc7a5ec79943d37d"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "a312b365160fb8c41c382c8ee35b30090d93c3f1819346445ecbb32805f83812"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+0/MSTM.v4.0.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[MSTM]]
arch = "i686"
git-tree-sha1 = "e2a6d6068b64efa7cbb070ecd9671716eb04e29f"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "284b7512b02b2a7beff6d18ae44a13bae405aefd60493920e27be6e3d6a58fd0"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+0/MSTM.v4.0.0.i686-linux-gnu-libgfortran3.tar.gz"
[[MSTM]]
arch = "i686"
git-tree-sha1 = "8f8629d97c7f8af3d621186f342382558181fc78"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "1302609086658f343099b5527bbf97519600404a3f15ea7fb8779e2d5393cced"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+0/MSTM.v4.0.0.i686-linux-gnu-libgfortran4.tar.gz"
[[MSTM]]
arch = "i686"
git-tree-sha1 = "5e2e2583ee0469236a53e506b3a64705ea16a967"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "4c2780e55647ec8ada4cdd2671ca060b04444785bea9691cfcb652a15f317e5e"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+0/MSTM.v4.0.0.i686-linux-gnu-libgfortran5.tar.gz"
[[MSTM]]
arch = "i686"
git-tree-sha1 = "2b411ddf936db306021726d1cf9e0b085eb97ecf"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "2beb0c3a3d85368a01247c22bfd3f862de2f5d4145c03fc8217fd6fb414a53b9"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+0/MSTM.v4.0.0.i686-linux-musl-libgfortran3.tar.gz"
[[MSTM]]
arch = "i686"
git-tree-sha1 = "83cca1f75eb164b8d2e31dd89d4c9ca907e74794"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "65c01f416fd4f4ba3b6d2d46a9dac8b0cf769af3f3f52855f93b22f276fec778"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+0/MSTM.v4.0.0.i686-linux-musl-libgfortran4.tar.gz"
[[MSTM]]
arch = "i686"
git-tree-sha1 = "a8eb813487b7938a1f120d5a5bb8c999af8ceb6f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "870235b4abb8b4b7d20b72c0f06b7da7935bd2c56bc400afabee2f614e8a3d0e"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+0/MSTM.v4.0.0.i686-linux-musl-libgfortran5.tar.gz"
[[MSTM]]
arch = "powerpc64le"
git-tree-sha1 = "4c68fdde1cb0f88f90d1f94445acf12090a42b78"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "b8539c8210a75e7cf2340033f12d3c7ce333f6c3250956e5f90bd6bf6821744e"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+0/MSTM.v4.0.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[MSTM]]
arch = "powerpc64le"
git-tree-sha1 = "ab0371e246ce12fd00e52c5ce23b47c4f4b3b558"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "9204b220d7515473db0cdc5c2d3a022983d34d6f8a7b52f356e6040cfccbd313"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+0/MSTM.v4.0.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[MSTM]]
arch = "powerpc64le"
git-tree-sha1 = "2ff756aed280ee8204f09b9b9451ca67622d1a8e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "a305ebc9a331164d4dceef8b082501d766c975350d013482a46945c473273033"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+0/MSTM.v4.0.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "0df45d0da5e6c90ecddcd23978493de04b669f99"
libgfortran_version = "3.0.0"
os = "macos"

    [[MSTM.download]]
    sha256 = "88f0038a4bbe185be7983b9ccab51a114e09eecea17951727ba5ec8738ff5589"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+0/MSTM.v4.0.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "dd7696faa1a3b51b0e9b5c45ee7615a12fdf8bf6"
libgfortran_version = "4.0.0"
os = "macos"

    [[MSTM.download]]
    sha256 = "beb8f19f0dde4cadac36ddcccb5928b8135f3b655b56ac51d9f2b441e997a441"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+0/MSTM.v4.0.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "cf0aa5223e18112f9d4d79dce7336ec00a87a05c"
libgfortran_version = "5.0.0"
os = "macos"

    [[MSTM.download]]
    sha256 = "46ec277659e26d14030cd6e2e24e8b0f5f2f9e4a57e1e4644acfd2a5f9d45ce3"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+0/MSTM.v4.0.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "9bfe38e12a7ec9caa267b96785982c3852751e9f"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "ed12b5d0975f65e0ac5eb1a5c1621e09302392b1cad4edfa26ea5724641d97fe"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+0/MSTM.v4.0.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "5109a594598772decb684b0c84411e6996e3acbb"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "a2bbe687e06aef9bfc8bff67a74654fbd3669e6175982a3ea5cc38df61daded8"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+0/MSTM.v4.0.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "d791fdd10c23bebe0382a25d6b49082d81aee53e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "151ff49f86e703548bc3b6ed3a667dc50e07c5d2c1108d641d421d02fbf78a47"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+0/MSTM.v4.0.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "bb389d865e3eed99b6f71997f942dadbfdc5d1df"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "23b7d4bd014aa2b49195df424f5b73c2542d28b3100b0c3be562cd3cccef4fd9"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+0/MSTM.v4.0.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "30e08af57db1a79899e8c6f40d89782d1ccbf404"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "6b9cf39c2ccfe8bd4019bf5139ad040ec38cf8605909bf79c40adb43cd9a9c94"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+0/MSTM.v4.0.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "7af58b0c4585d7a296006c5aafaac9bf364500a2"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MSTM.download]]
    sha256 = "8c7422ab7857a807e7521a1eb68925dd9c0509b845015f9395d36374ac6e591e"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+0/MSTM.v4.0.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "191a2eba3f68c324b1ca6698d074293f70c0385d"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[MSTM.download]]
    sha256 = "9eccb1474383d03c0fc622cef569ba862f76ff74b749f3c60fde0656d945d5e4"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+0/MSTM.v4.0.0.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "927bd99d25f57a60f7dc039653bf02064720d460"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[MSTM.download]]
    sha256 = "d10e581db0d9b846fd431956832ed51175be0d5763b4b4fe37d8a49d2819baf9"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+0/MSTM.v4.0.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[MSTM]]
arch = "x86_64"
git-tree-sha1 = "e1d5e724e21974b57bb2ee70c85326706a97907b"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[MSTM.download]]
    sha256 = "bfe78b785e33b97db3204aecb0e367f37cfe6ef2fa4f0f5c539173ea22eb0618"
    url = "https://github.com/JuliaBinaryWrappers/MSTM_jll.jl/releases/download/MSTM-v4.0.0+0/MSTM.v4.0.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
