# Autogenerated wrapper script for MSTM_jll for x86_64-unknown-freebsd-libgfortran5-mpi+mpich
export mstm

using CompilerSupportLibraries_jll
using MPICH_jll
using MPIPreferences
JLLWrappers.@generate_wrapper_header("MSTM")
JLLWrappers.@declare_executable_product(mstm)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, MPICH_jll, MPIPreferences)
    JLLWrappers.@init_executable_product(
        mstm,
        "bin/mstm",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
